spring:
  profiles:
    active: local
  batch:
    jdbc:
      isolation-level-for-create:
  logging:
    level:
      root: INFO
      org.hibernate.SQL: debug
server.port: 7000

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:mem:tmplDs
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console